### PR TITLE
allow empty data to be passed in to runSingle. fixes #23

### LINKED ISSUE #23: Default data on api/run
Posting without a payload doesn't run the job.

### PR DESCRIPTION
**Pull request by jgallen23**

### CODE REVIEW

**Comment by jgallen23** [comment]
no idea why these are failing.  @dawnerd when you have a sec, can you take a look?

**Comment by jgallen23** [comment]
so they pass here, but not on my local box.  odd

**Comment by dawnerd** [comment]
That is really weird. Whats the error?

**Comment by jgallen23** [comment]
Same thing I sent to you in hipchat earlier. I'll try clearing mongo and see what happens tomorrow

**Pull request merged**
